### ISSUE TITLE
Swipe sensitivity

### ISSUE THREAD

**Issue by erichsalvesen** [freerunnering/SwipeSelection#59] opened 2015-03-10 18:07 UTC
Swipe sensitivity is too high and registers the slightest brush of a finger over the keyboard while maneuvering between letters as a swipe and makes typing an unnecessary pain as the cursor is constantly being forced back a few spaces as I type.

**Comment by freerunnering** [comment] 2015-07-08 15:13
Duplicate of #32

**Closed by freerunnering** 2015-07-08 15:13 UTC
